version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./app/backend:/usr/app-back
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:changeme@db:5432/postgres
      - JWT_SECRET_KEY=secret_test_key
    depends_on:
      - db
    ports:
      - 3001:3001
      - 5555:5555
    networks:
      - net

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
    postgres:
